// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "kubevault.dev/operator/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// VaultServers returns a VaultServerInformer.
	VaultServers() VaultServerInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// VaultServers returns a VaultServerInformer.
func (v *version) VaultServers() VaultServerInformer {
	return &vaultServerInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
