// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// VaultServerVersionListerExpansion allows custom methods to be added to
// VaultServerVersionLister.
type VaultServerVersionListerExpansion interface{}
