// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "kubevault.dev/operator/apis/catalog/v1alpha1"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// VaultServerVersionLister helps list VaultServerVersions.
type VaultServerVersionLister interface {
	// List lists all VaultServerVersions in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.VaultServerVersion, err error)
	// Get retrieves the VaultServerVersion from the index for a given name.
	Get(name string) (*v1alpha1.VaultServerVersion, error)
	VaultServerVersionListerExpansion
}

// vaultServerVersionLister implements the VaultServerVersionLister interface.
type vaultServerVersionLister struct {
	indexer cache.Indexer
}

// NewVaultServerVersionLister returns a new VaultServerVersionLister.
func NewVaultServerVersionLister(indexer cache.Indexer) VaultServerVersionLister {
	return &vaultServerVersionLister{indexer: indexer}
}

// List lists all VaultServerVersions in the indexer.
func (s *vaultServerVersionLister) List(selector labels.Selector) (ret []*v1alpha1.VaultServerVersion, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.VaultServerVersion))
	})
	return ret, err
}

// Get retrieves the VaultServerVersion from the index for a given name.
func (s *vaultServerVersionLister) Get(name string) (*v1alpha1.VaultServerVersion, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("vaultserverversion"), name)
	}
	return obj.(*v1alpha1.VaultServerVersion), nil
}
