// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "kubevault.dev/operator/client/clientset/versioned/typed/kubevault/v1alpha1"

	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeKubevaultV1alpha1 struct {
	*testing.Fake
}

func (c *FakeKubevaultV1alpha1) VaultServers(namespace string) v1alpha1.VaultServerInterface {
	return &FakeVaultServers{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeKubevaultV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
