// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AWSAccessKeyRequestListerExpansion allows custom methods to be added to
// AWSAccessKeyRequestLister.
type AWSAccessKeyRequestListerExpansion interface{}

// AWSAccessKeyRequestNamespaceListerExpansion allows custom methods to be added to
// AWSAccessKeyRequestNamespaceLister.
type AWSAccessKeyRequestNamespaceListerExpansion interface{}

// AWSRoleListerExpansion allows custom methods to be added to
// AWSRoleLister.
type AWSRoleListerExpansion interface{}

// AWSRoleNamespaceListerExpansion allows custom methods to be added to
// AWSRoleNamespaceLister.
type AWSRoleNamespaceListerExpansion interface{}

// AzureAccessKeyRequestListerExpansion allows custom methods to be added to
// AzureAccessKeyRequestLister.
type AzureAccessKeyRequestListerExpansion interface{}

// AzureAccessKeyRequestNamespaceListerExpansion allows custom methods to be added to
// AzureAccessKeyRequestNamespaceLister.
type AzureAccessKeyRequestNamespaceListerExpansion interface{}

// AzureRoleListerExpansion allows custom methods to be added to
// AzureRoleLister.
type AzureRoleListerExpansion interface{}

// AzureRoleNamespaceListerExpansion allows custom methods to be added to
// AzureRoleNamespaceLister.
type AzureRoleNamespaceListerExpansion interface{}

// DatabaseAccessRequestListerExpansion allows custom methods to be added to
// DatabaseAccessRequestLister.
type DatabaseAccessRequestListerExpansion interface{}

// DatabaseAccessRequestNamespaceListerExpansion allows custom methods to be added to
// DatabaseAccessRequestNamespaceLister.
type DatabaseAccessRequestNamespaceListerExpansion interface{}

// GCPAccessKeyRequestListerExpansion allows custom methods to be added to
// GCPAccessKeyRequestLister.
type GCPAccessKeyRequestListerExpansion interface{}

// GCPAccessKeyRequestNamespaceListerExpansion allows custom methods to be added to
// GCPAccessKeyRequestNamespaceLister.
type GCPAccessKeyRequestNamespaceListerExpansion interface{}

// GCPRoleListerExpansion allows custom methods to be added to
// GCPRoleLister.
type GCPRoleListerExpansion interface{}

// GCPRoleNamespaceListerExpansion allows custom methods to be added to
// GCPRoleNamespaceLister.
type GCPRoleNamespaceListerExpansion interface{}

// MongoDBRoleListerExpansion allows custom methods to be added to
// MongoDBRoleLister.
type MongoDBRoleListerExpansion interface{}

// MongoDBRoleNamespaceListerExpansion allows custom methods to be added to
// MongoDBRoleNamespaceLister.
type MongoDBRoleNamespaceListerExpansion interface{}

// MySQLRoleListerExpansion allows custom methods to be added to
// MySQLRoleLister.
type MySQLRoleListerExpansion interface{}

// MySQLRoleNamespaceListerExpansion allows custom methods to be added to
// MySQLRoleNamespaceLister.
type MySQLRoleNamespaceListerExpansion interface{}

// PostgresRoleListerExpansion allows custom methods to be added to
// PostgresRoleLister.
type PostgresRoleListerExpansion interface{}

// PostgresRoleNamespaceListerExpansion allows custom methods to be added to
// PostgresRoleNamespaceLister.
type PostgresRoleNamespaceListerExpansion interface{}

// SecretEngineListerExpansion allows custom methods to be added to
// SecretEngineLister.
type SecretEngineListerExpansion interface{}

// SecretEngineNamespaceListerExpansion allows custom methods to be added to
// SecretEngineNamespaceLister.
type SecretEngineNamespaceListerExpansion interface{}
