// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type AWSAccessKeyRequestExpansion interface{}

type AWSRoleExpansion interface{}

type AzureAccessKeyRequestExpansion interface{}

type AzureRoleExpansion interface{}

type DatabaseAccessRequestExpansion interface{}

type GCPAccessKeyRequestExpansion interface{}

type GCPRoleExpansion interface{}

type MongoDBRoleExpansion interface{}

type MySQLRoleExpansion interface{}

type PostgresRoleExpansion interface{}

type SecretEngineExpansion interface{}
