// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// VaultServerListerExpansion allows custom methods to be added to
// VaultServerLister.
type VaultServerListerExpansion interface{}

// VaultServerNamespaceListerExpansion allows custom methods to be added to
// VaultServerNamespaceLister.
type VaultServerNamespaceListerExpansion interface{}
