// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "kubevault.dev/operator/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// VaultPolicies returns a VaultPolicyInformer.
	VaultPolicies() VaultPolicyInformer
	// VaultPolicyBindings returns a VaultPolicyBindingInformer.
	VaultPolicyBindings() VaultPolicyBindingInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// VaultPolicies returns a VaultPolicyInformer.
func (v *version) VaultPolicies() VaultPolicyInformer {
	return &vaultPolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VaultPolicyBindings returns a VaultPolicyBindingInformer.
func (v *version) VaultPolicyBindings() VaultPolicyBindingInformer {
	return &vaultPolicyBindingInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
